version: "3.8"

services:
  # Backend (NestJS)
  backend:
    image: registry.gitlab.com/tada-project/backend:test
    container_name: tada-backend-test
    environment:
      - NODE_ENV=test
    env_file:
      - .env.test
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - tada-network

  # Frontend (Next.js)
  frontend:
    image: registry.gitlab.com/tada-project/frontend:test
    container_name: tada-frontend-test
    environment:
      - NODE_ENV=production
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - tada-network

  # Nginx (if not using system nginx)
  # nginx:
  #   image: nginx:alpine
  #   container_name: tada-nginx-test
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/ssl:/etc/nginx/ssl
  #     - ./nginx/logs:/var/log/nginx
  #   depends_on:
  #     - backend
  #     - frontend
  #   restart: unless-stopped
  #   networks:
  #     - tada-network

networks:
  tada-network:
    driver: bridge
