import { baseApi } from "@/store/api/baseApi";
import { Property } from "@/app/types/property";
import { normalizeProperty } from "@/store/api/properties.api";

/** One scored category of a match, as the backend calculates it. */
export interface MatchCategory {
  category: string;
  match: boolean;
  score: number;
  maxScore: number;
  reason: string;
  details?: string;
  hasPreference: boolean;
}

export interface MatchedPropertyItem {
  property: Property;
  matchScore: number;
  categories: MatchCategory[];
}

/** Envelope of `GET /matching/matched-properties`. */
export interface MatchedPropertiesPage {
  data: MatchedPropertyItem[];
  total: number;
  page: number;
  totalPages: number;
  /**
   * Mean match score over the whole matched set — the population `total`
   * counts, not the page in `data`. `null` when nothing was scored (a user
   * with no preferences, or a search that matched no property), and absent
   * from a payload served by a backend older than this field.
   */
  avgMatchScore?: number | null;
  /**
   * Present only when an admin requested the feed with `asUserId` (the "view
   * as tenant" lens): the tenant the page is scored for, named for the
   * admin's banner. A tenant's own feed never carries it.
   */
  viewingAs?: ViewingAs;
}

/** The tenant an admin's "view as" feed is scored for. */
export interface ViewingAs {
  id: string;
  full_name: string | null;
  /**
   * Token behind the tenant's public `/cv/{token}` page; null when they have
   * never shared their CV. Optional so a payload from an older backend still
   * types.
   */
  tenant_cv_share_uuid?: string | null;
}

/**
 * The `sort` values `GET /matching/matched-properties` accepts, mirroring the
 * backend's `MATCHED_PROPERTIES_SORTS`.
 *
 * Hand-written rather than taken from `@/types/generated/api.d.ts`: that file
 * is generated by `npm run gen:api` (which needs the backend's `openapi:dump`)
 * and has not been regenerated since this parameter was added. Swap this for
 * the generated schema type the next time the types are refreshed — the same
 * follow-up `frontend/src/app/lib/callRequest.ts` already carries.
 */
export type MatchedPropertiesSort =
  | "best_match"
  | "low_price"
  | "high_price"
  | "low_deposit"
  | "high_deposit"
  | "date_added";

export interface GetMatchedPropertiesArgs {
  page?: number;
  limit?: number;
  search?: string;
  /**
   * Server-side ordering of the whole listed inventory. Omitted from the query
   * string when absent, which the backend reads as `best_match`.
   */
  sort?: MatchedPropertiesSort;
  /**
   * Admin only: score against this tenant's preferences instead of the
   * caller's. The backend answers 403 for any other role, so the client only
   * sends it for an admin. Part of the cache key, so the admin's own feed and
   * each tenant's are separate entries.
   */
  asUserId?: string;
}

/** Args of `GET /matching/property/:id`; a bare id is the caller's own match. */
export type GetPropertyMatchArgs =
  string | { propertyId: string; asUserId?: string };

/** Args of `POST /matching/scores`; a bare id list is the caller's own scores. */
export type GetMatchScoresArgs =
  string[] | { propertyIds: string[]; asUserId?: string };

const propertyMatchArgs = (args: GetPropertyMatchArgs) =>
  typeof args === "string" ? { propertyId: args } : args;

const matchScoresArgs = (args: GetMatchScoresArgs) =>
  Array.isArray(args) ? { propertyIds: args } : args;

/** `GET /matching/property/:id` — the backend's PropertyMatchResult. */
export interface PropertyMatchResult {
  property: Property;
  totalScore: number;
  maxPossibleScore: number;
  matchPercentage: number;
  isPerfectMatch: boolean;
  categories: MatchCategory[];
  summary: {
    matched: number;
    partial: number;
    notMatched: number;
    skipped: number;
  };
}

/** One property's score as the card grids consume it. */
export interface PropertyMatchScore {
  matchScore: number;
  categories: MatchCategory[];
}

/** Envelope of `POST /matching/scores`, keyed by property id. */
export interface MatchScoresResponse {
  scores: Record<string, PropertyMatchScore>;
}

/**
 * Read endpoints of the matching domain. All of them require a session — none
 * goes into the base query's public endpoints. The backend's full-table scoring
 * pass and its presigning loop stay with the next sub-PR of Phase 6.2.
 */
export const matchingApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    /**
     * The full listed inventory, paginated and ordered server-side. Every sort
     * of the results feed reads this one endpoint: `sort` decides the order,
     * `total` is the whole listed count either way, and each item carries its
     * own real match score for the card badge.
     */
    getMatchedProperties: builder.query<
      MatchedPropertiesPage,
      GetMatchedPropertiesArgs | void
    >({
      query: (args) => ({
        url: "/matching/matched-properties",
        params: {
          page: args?.page ?? 1,
          limit: args?.limit ?? 12,
          ...(args?.search ? { search: args.search } : {}),
          ...(args?.sort ? { sort: args.sort } : {}),
          ...(args?.asUserId ? { asUserId: args.asUserId } : {}),
        },
      }),
      // The matching route serves raw entities, so the same decimal-string
      // normalisation the properties endpoints do applies to each item.
      transformResponse: (page: MatchedPropertiesPage) => ({
        ...page,
        data: page.data.map((item) => ({
          ...item,
          property: normalizeProperty(item.property),
        })),
      }),
      providesTags: (result) =>
        result
          ? [
              ...result.data.map(({ property }) => ({
                type: "Property" as const,
                id: property.id,
              })),
              { type: "Property" as const, id: "MATCHED_LIST" },
            ]
          : [{ type: "Property" as const, id: "MATCHED_LIST" }],
    }),

    /**
     * Match breakdown for one property; 404s when preferences are missing.
     * The whole arg is the cache key, so an admin's view-as breakdown never
     * shares an entry with their own.
     */
    getPropertyMatch: builder.query<PropertyMatchResult, GetPropertyMatchArgs>({
      query: (args) => {
        const { propertyId, asUserId } = propertyMatchArgs(args);
        return {
          url: `/matching/property/${propertyId}`,
          params: asUserId ? { asUserId } : undefined,
        };
      },
      providesTags: (_result, _error, args) => [
        { type: "Property", id: propertyMatchArgs(args).propertyId },
      ],
    }),

    /**
     * Scores for a whole grid in one request. A POST because a grid's worth of
     * UUIDs does not belong in a URL, but a query rather than a mutation: it
     * reads, so it must stay cached and deduplicated like any other read.
     *
     * The ids are sorted into the cache key, so two grids showing the same
     * properties in a different order share one cache entry and one request.
     * An admin's `asUserId` is part of the key too — without it the admin's
     * own scores and a tenant's would collide in one entry.
     */
    getMatchScores: builder.query<MatchScoresResponse, GetMatchScoresArgs>({
      query: (args) => {
        const { propertyIds, asUserId } = matchScoresArgs(args);
        return {
          url: "/matching/scores",
          method: "POST",
          body: { propertyIds },
          params: asUserId ? { asUserId } : undefined,
        };
      },
      serializeQueryArgs: ({ endpointName, queryArgs }) => {
        const { propertyIds, asUserId } = matchScoresArgs(queryArgs);
        const ids = [...propertyIds].sort().join(",");
        return asUserId
          ? `${endpointName}(${ids})@${asUserId}`
          : `${endpointName}(${ids})`;
      },
      providesTags: (result) =>
        result
          ? [
              ...Object.keys(result.scores).map((id) => ({
                type: "Property" as const,
                id,
              })),
              { type: "Property" as const, id: "MATCH_SCORES" },
            ]
          : [{ type: "Property" as const, id: "MATCH_SCORES" }],
    }),
  }),
});

export const {
  useGetMatchedPropertiesQuery,
  useGetPropertyMatchQuery,
  useGetMatchScoresQuery,
} = matchingApi;
