/**
 * Shared constants for admin forms (Building and Property creation/editing)
 * These should be used instead of hardcoded arrays in components
 */

// ==================== TENANT TYPES ====================
export const TENANT_TYPE_OPTIONS = [
  { value: "corporateLets", label: "Corporate Lets" },
  { value: "sharers", label: "Sharers" },
  { value: "student", label: "Student" },
  { value: "family", label: "Family" },
  { value: "elder", label: "Elder" },
] as const;

// ==================== AMENITIES ====================
// Same categories and values as preferences Step 7 (AmenitiesStep) for consistency.
export const AMENITIES_BY_CATEGORY = [
  {
    title: "Facilities & Workspace",
    values: [
      "Gym",
      "Co-working",
      "Meeting rooms",
      "Lounge",
      "Cinema",
      "Roof terrace",
      "Courtyard",
      "Parking",
      "Bike storage",
      "Parcel room",
    ],
  },
  {
    title: "Services & Community",
    values: [
      "Maintenance",
      "Events calendar",
      "Pet areas",
      "Kids' room",
      "Garden",
    ],
  },
  {
    title: "Lifestyle & Culture",
    values: ["Reading", "Music", "Art"],
  },
  {
    title: "Outdoor & Activities",
    values: ["Hiking", "Cooking"],
  },
  {
    title: "Wellbeing & Sport",
    values: ["Travel", "Sport"],
  },
] as const;

/** Flat list of all amenities (for backward compatibility and simple dropdowns). */
export const AMENITIES_OPTIONS: readonly string[] =
  AMENITIES_BY_CATEGORY.flatMap((s) => s.values);

// ==================== BUILDING UNIT TYPES (Type of Unit) ====================
// Same 6 options as preferences Step 3 (Property type). Form stores UI strings; save/load via mappings.
export const TYPE_OF_UNIT_OPTIONS = [
  "Apartment",
  "Flat",
  "Studio",
  "Penthouse",
  "En-suite room",
  "Room",
] as const;

// ==================== PROPERTY TYPES ====================
export const PROPERTY_TYPE_OPTIONS = [
  { value: "apartment", label: "Apartment" },
  { value: "flat", label: "Flat" },
  { value: "studio", label: "Studio" },
  { value: "penthouse", label: "Penthouse" },
  { value: "room", label: "Room" },
  { value: "house", label: "House" },
] as const;

// ==================== FURNISHING OPTIONS ====================
export const FURNISHING_OPTIONS = [
  { value: "furnished", label: "Furnished" },
  { value: "unfurnished", label: "Unfurnished" },
  { value: "part_furnished", label: "Part-furnished" },
  { value: "designer_furniture", label: "Designer furniture" },
] as const;

// ==================== OUTDOOR SPACE OPTIONS ====================
export const OUTDOOR_SPACE_OPTIONS = [
  { value: "outdoor_space", label: "Outdoor Space" },
  { value: "balcony", label: "Balcony" },
  { value: "terrace", label: "Terrace" },
] as const;

// ==================== ROOMS/BEDROOMS OPTIONS ====================
export const BEDROOMS_OPTIONS = [
  { value: 0, label: "Studio" },
  { value: 1, label: "1 bedroom" },
  { value: 2, label: "2 bedrooms" },
  { value: 3, label: "3 bedrooms" },
  { value: 4, label: "4 bedrooms" },
  { value: 5, label: "5+ bedrooms" },
] as const;

// ==================== BATHROOMS OPTIONS ====================
export const BATHROOMS_OPTIONS = [
  { value: 1, label: "1 bathroom" },
  { value: 2, label: "2 bathrooms" },
  { value: 3, label: "3 bathrooms" },
  { value: 4, label: "4+ bathrooms" },
] as const;

// ==================== AREAS (Areas of London) ====================
export const AREA_OPTIONS = [
  "Central London",
  "North London",
  "East London",
  "South London",
  "West London",
] as const;

// ==================== LONDON DISTRICTS (grouped by area) ====================
export const DISTRICTS_BY_AREA: {
  area: string;
  districts: readonly string[];
}[] = [
  {
    area: "Central London",
    districts: [
      "Camden",
      "Westminster",
      "Kensington and Chelsea",
      "Islington",
      "Lambeth",
      "Southwark",
    ],
  },
  {
    area: "North London",
    districts: ["Barnet", "Enfield", "Haringey", "Camden", "Islington"],
  },
  {
    area: "East London",
    districts: [
      "Hackney",
      "Tower Hamlets",
      "Newham",
      "Barking and Dagenham",
      "Waltham Forest",
      "Redbridge",
      "Havering",
    ],
  },
  {
    area: "South London",
    districts: [
      "Lambeth",
      "Southwark",
      "Lewisham",
      "Greenwich",
      "Wandsworth",
      "Croydon",
      "Bromley",
      "Merton",
      "Kingston upon Thames",
    ],
  },
  {
    area: "West London",
    districts: [
      "Hammersmith and Fulham",
      "Ealing",
      "Hounslow",
      "Brent",
      "Hillingdon",
      "Kensington and Chelsea",
      "Richmond upon Thames",
    ],
  },
];

/** Flat list of all districts (unique, order follows areas). Used by building modals and as fallback. */
const _DISTRICTS_FLAT = DISTRICTS_BY_AREA.flatMap((g) => g.districts);
export const LONDON_DISTRICTS: readonly string[] = [
  ...new Set(_DISTRICTS_FLAT),
];

// ==================== LONDON METRO STATIONS ====================
export const LONDON_METRO_STATIONS: readonly string[] = [
  "Acton Town",
  "Aldgate",
  "Aldgate East",
  "Alperton",
  "Amersham",
  "Angel",
  "Archway",
  "Arnos Grove",
  "Arsenal",
  "Baker Street",
  "Balham",
  "Bank",
  "Barbican",
  "Barking",
  "Barkingside",
  "Barons Court",
  "Bayswater",
  "Becontree",
  "Belsize Park",
  "Bermondsey",
  "Bethnal Green",
  "Blackfriars",
  "Blackhorse Road",
  "Bond Street",
  "Borough",
  "Boston Manor",
  "Bounds Green",
  "Bow Road",
  "Brent Cross",
  "Brixton",
  "Bromley-by-Bow",
  "Buckhurst Hill",
  "Burnt Oak",
  "Caledonian Road",
  "Camden Town",
  "Canada Water",
  "Canary Wharf",
  "Canning Town",
  "Cannon Street",
  "Chalk Farm",
  "Chancery Lane",
  "Charing Cross",
  "Chesham",
  "Chigwell",
  "Chiswick Park",
  "Chorleywood",
  "Clapham Common",
  "Clapham North",
  "Clapham South",
  "Cockfosters",
  "Colindale",
  "Colliers Wood",
  "Covent Garden",
  "Croxley",
  "Dagenham East",
  "Dagenham Heathway",
  "Debden",
  "Dollis Hill",
  "Ealing Broadway",
  "Ealing Common",
  "Earl's Court",
  "East Acton",
  "East Finchley",
  "East Ham",
  "East Putney",
  "Edgware",
  "Edgware Road",
  "Elephant & Castle",
  "Elm Park",
  "Embankment",
  "Epping",
  "Euston",
  "Euston Square",
  "Fairlop",
  "Farringdon",
  "Finchley Central",
  "Finchley Road",
  "Finsbury Park",
  "Fulham Broadway",
  "Gants Hill",
  "Gloucester Road",
  "Golders Green",
  "Goodge Street",
  "Green Park",
  "Greenford",
  "Gunnersbury",
  "Hainault",
  "Hammersmith",
  "Hampstead",
  "Hanger Lane",
  "Harlesden",
  "Harrow & Wealdstone",
  "Harrow-on-the-Hill",
  "Hatton Cross",
  "Heathrow Terminal 4",
  "Heathrow Terminal 5",
  "Heathrow Terminals 2 & 3",
  "Hendon Central",
  "High Barnet",
  "High Street Kensington",
  "Highbury & Islington",
  "Highgate",
  "Hillingdon",
  "Holborn",
  "Holland Park",
  "Holloway Road",
  "Hornchurch",
  "Hounslow Central",
  "Hounslow East",
  "Hounslow West",
  "Hyde Park Corner",
  "Ickenham",
  "Kennington",
  "Kensal Green",
  "Kensington (Olympia)",
  "Kentish Town",
  "Kenton",
  "Kew Gardens",
  "Kilburn",
  "Kilburn Park",
  "King's Cross St Pancras",
  "Knightsbridge",
  "Ladbroke Grove",
  "Lambeth North",
  "Lancaster Gate",
  "Latimer Road",
  "Leicester Square",
  "Leyton",
  "Leytonstone",
  "Liverpool Street",
  "London Bridge",
  "Loughton",
  "Maida Vale",
  "Manor House",
  "Mansion House",
  "Marble Arch",
  "Marylebone",
  "Mile End",
  "Mill Hill East",
  "Monument",
  "Moor Park",
  "Moorgate",
  "Morden",
  "Mornington Crescent",
  "Neasden",
  "Newbury Park",
  "North Acton",
  "North Ealing",
  "North Greenwich",
  "Northfields",
  "Northolt",
  "Northwick Park",
  "Northwood",
  "Northwood Hills",
  "Notting Hill Gate",
  "Oakwood",
  "Old Street",
  "Osterley",
  "Oval",
  "Oxford Circus",
  "Paddington",
  "Park Royal",
  "Parsons Green",
  "Perivale",
  "Piccadilly Circus",
  "Pimlico",
  "Pinner",
  "Plaistow",
  "Preston Road",
  "Putney Bridge",
  "Queen's Park",
  "Queensbury",
  "Queensway",
  "Ravenscourt Park",
  "Redbridge",
  "Regent's Park",
  "Richmond",
  "Rickmansworth",
  "Roding Valley",
  "Royal Oak",
  "Ruislip",
  "Ruislip Gardens",
  "Ruislip Manor",
  "Russell Square",
  "Seven Sisters",
  "Shepherd's Bush",
  "Shepherd's Bush Market",
  "Sloane Square",
  "South Ealing",
  "South Harrow",
  "South Kensington",
  "South Ruislip",
  "South Wimbledon",
  "Southfields",
  "Southgate",
  "Southwark",
  "St James's Park",
  "St John's Wood",
  "St Paul's",
  "Stamford Brook",
  "Stanmore",
  "Stepney Green",
  "Stockwell",
  "Stratford",
  "Sudbury Hill",
  "Sudbury Town",
  "Surrey Quays",
  "Swiss Cottage",
  "Temple",
  "Theydon Bois",
  "Tooting Bec",
  "Tooting Broadway",
  "Tottenham Court Road",
  "Tottenham Hale",
  "Totteridge & Whetstone",
  "Tower Hill",
  "Tufnell Park",
  "Turnham Green",
  "Turnpike Lane",
  "Upminster",
  "Upminster Bridge",
  "Upney",
  "Uxbridge",
  "Vauxhall",
  "Victoria",
  "Walthamstow Central",
  "Wanstead",
  "Warren Street",
  "Warwick Avenue",
  "Waterloo",
  "Watford",
  "Wembley Central",
  "Wembley Park",
  "West Acton",
  "West Brompton",
  "West Finchley",
  "West Ham",
  "West Hampstead",
  "West Harrow",
  "West Kensington",
  "West Ruislip",
  "Westbourne Park",
  "Westminster",
  "White City",
  "Whitechapel",
  "Willesden Green",
  "Willesden Junction",
  "Wimbledon",
  "Wimbledon Park",
  "Wood Green",
  "Woodford",
  "Woodside Park",
];

// ==================== PET TYPES ====================
export const PET_TYPE_OPTIONS = [
  { value: "dog", label: "Dog" },
  { value: "cat", label: "Cat" },
  { value: "other", label: "Other" },
] as const;

export const PET_SIZE_OPTIONS = [
  { value: "small", label: "Small" },
  { value: "medium", label: "Medium" },
  { value: "large", label: "Large" },
] as const;
