import { MigrationInterface, QueryRunner } from "typeorm";

export class AddDeposit1764203300507 implements MigrationInterface {
    name = 'AddDeposit1764203300507'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "preferences" DROP CONSTRAINT "FK_preferences_user_id"`);
        await queryRunner.query(`ALTER TABLE "tenant_profiles" DROP CONSTRAINT "FK_tenant_profiles_userId"`);
        await queryRunner.query(`ALTER TABLE "operator_profiles" DROP CONSTRAINT "FK_operator_profiles_userId"`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP CONSTRAINT "FK_buildings_operator"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP CONSTRAINT "FK_properties_operator_id"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP CONSTRAINT "FK_properties_building"`);
        await queryRunner.query(`ALTER TABLE "shortlist" DROP CONSTRAINT "FK_shortlist_userId"`);
        await queryRunner.query(`ALTER TABLE "shortlist" DROP CONSTRAINT "FK_shortlist_propertyId"`);
        await queryRunner.query(`ALTER TABLE "property_media" DROP CONSTRAINT "FK_property_media_property_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_preferences_property_type_gin"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_preferences_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_properties_price"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_properties_bedrooms"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_properties_available_from"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_properties_lifestyle_features"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_properties_property_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_shortlist_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_google_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_full_name"`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP CONSTRAINT "CHK_type_of_unit"`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP CONSTRAINT "CHK_tenant_type"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "furnishing"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "lifestyle_features"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "available_from"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "images"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "is_btr"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "lat"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "lng"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "property_type"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "descriptions"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "bills"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "building_type"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "let_duration"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "floor"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "outdoor_space"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "balcony"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "terrace"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "square_meters"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "video"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP COLUMN "documents"`);
        await queryRunner.query(`ALTER TABLE "preferences" ADD CONSTRAINT "UQ_34a542d34f1c75c43e78df2e67a" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP COLUMN "type_of_unit"`);
        await queryRunner.query(`CREATE TYPE "public"."buildings_type_of_unit_enum" AS ENUM('studio', '1-bed', '2-bed', '3-bed', 'Duplex', 'penthouse')`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD "type_of_unit" "public"."buildings_type_of_unit_enum"`);
        await queryRunner.query(`ALTER TABLE "buildings" ALTER COLUMN "metro_stations" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "buildings" ALTER COLUMN "commute_times" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "buildings" ALTER COLUMN "local_essentials" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "buildings" ALTER COLUMN "amenities" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "buildings" ALTER COLUMN "is_concierge" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP COLUMN "tenant_type"`);
        await queryRunner.query(`CREATE TYPE "public"."buildings_tenant_type_enum" AS ENUM('corporateLets', 'sharers', 'student', 'family', 'elder')`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD "tenant_type" "public"."buildings_tenant_type_enum" DEFAULT 'family'`);
        await queryRunner.query(`ALTER TABLE "buildings" ALTER COLUMN "operator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "properties" ALTER COLUMN "building_id" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "preferences" ADD CONSTRAINT "FK_34a542d34f1c75c43e78df2e67a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_profiles" ADD CONSTRAINT "FK_b8a59063604d0b6d659548da5a9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "operator_profiles" ADD CONSTRAINT "FK_7a8bd6902d3eff8546548e6e69e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD CONSTRAINT "FK_0bd1c6abc1930515bbce4eb2441" FOREIGN KEY ("operator_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "properties" ADD CONSTRAINT "FK_0bfd8f2ef727798734b537ef222" FOREIGN KEY ("operator_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "properties" ADD CONSTRAINT "FK_596505820276c00d0fa9f827b43" FOREIGN KEY ("building_id") REFERENCES "buildings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shortlist" ADD CONSTRAINT "FK_324279f59659fdb6ad0eb6f8942" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shortlist" ADD CONSTRAINT "FK_683115c3f00d8f904dd359a95ab" FOREIGN KEY ("propertyId") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_media" ADD CONSTRAINT "FK_8f44a07b8e344393e360b2dd808" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "property_media" DROP CONSTRAINT "FK_8f44a07b8e344393e360b2dd808"`);
        await queryRunner.query(`ALTER TABLE "shortlist" DROP CONSTRAINT "FK_683115c3f00d8f904dd359a95ab"`);
        await queryRunner.query(`ALTER TABLE "shortlist" DROP CONSTRAINT "FK_324279f59659fdb6ad0eb6f8942"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP CONSTRAINT "FK_596505820276c00d0fa9f827b43"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP CONSTRAINT "FK_0bfd8f2ef727798734b537ef222"`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP CONSTRAINT "FK_0bd1c6abc1930515bbce4eb2441"`);
        await queryRunner.query(`ALTER TABLE "operator_profiles" DROP CONSTRAINT "FK_7a8bd6902d3eff8546548e6e69e"`);
        await queryRunner.query(`ALTER TABLE "tenant_profiles" DROP CONSTRAINT "FK_b8a59063604d0b6d659548da5a9"`);
        await queryRunner.query(`ALTER TABLE "preferences" DROP CONSTRAINT "FK_34a542d34f1c75c43e78df2e67a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`ALTER TABLE "properties" ALTER COLUMN "building_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "buildings" ALTER COLUMN "operator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP COLUMN "tenant_type"`);
        await queryRunner.query(`DROP TYPE "public"."buildings_tenant_type_enum"`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD "tenant_type" character varying DEFAULT 'family'`);
        await queryRunner.query(`ALTER TABLE "buildings" ALTER COLUMN "is_concierge" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "buildings" ALTER COLUMN "amenities" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "buildings" ALTER COLUMN "local_essentials" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "buildings" ALTER COLUMN "commute_times" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "buildings" ALTER COLUMN "metro_stations" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "buildings" DROP COLUMN "type_of_unit"`);
        await queryRunner.query(`DROP TYPE "public"."buildings_type_of_unit_enum"`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD "type_of_unit" character varying`);
        await queryRunner.query(`ALTER TABLE "preferences" DROP CONSTRAINT "UQ_34a542d34f1c75c43e78df2e67a"`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "documents" character varying`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "video" character varying`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "square_meters" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "terrace" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "balcony" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "outdoor_space" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "floor" integer`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "let_duration" character varying DEFAULT 'any'`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "building_type" character varying`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "bills" character varying DEFAULT 'excluded'`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "descriptions" text`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "property_type" character varying DEFAULT 'apartment'`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "lng" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "lat" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "is_btr" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "images" text`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "available_from" date`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "lifestyle_features" text`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "furnishing" character varying`);
        await queryRunner.query(`ALTER TABLE "properties" ADD "address" character varying`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD CONSTRAINT "CHK_tenant_type" CHECK (((tenant_type IS NULL) OR ((tenant_type)::text = ANY ((ARRAY['corporateLets'::character varying, 'sharers'::character varying, 'student'::character varying, 'family'::character varying, 'elder'::character varying])::text[]))))`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD CONSTRAINT "CHK_type_of_unit" CHECK (((type_of_unit IS NULL) OR ((type_of_unit)::text = ANY ((ARRAY['studio'::character varying, '1-bed'::character varying, '2-bed'::character varying, '3-bed'::character varying, 'Duplex'::character varying, 'penthouse'::character varying])::text[]))))`);
        await queryRunner.query(`CREATE INDEX "IDX_users_full_name" ON "users" ("full_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_google_id" ON "users" ("google_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_shortlist_userId" ON "shortlist" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_properties_property_type" ON "properties" ("property_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_properties_lifestyle_features" ON "properties" ("lifestyle_features") `);
        await queryRunner.query(`CREATE INDEX "IDX_properties_available_from" ON "properties" ("available_from") `);
        await queryRunner.query(`CREATE INDEX "IDX_properties_bedrooms" ON "properties" ("bedrooms") `);
        await queryRunner.query(`CREATE INDEX "IDX_properties_price" ON "properties" ("price") `);
        await queryRunner.query(`CREATE INDEX "IDX_preferences_user_id" ON "preferences" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_preferences_property_type_gin" ON "preferences" ("property_type") `);
        await queryRunner.query(`ALTER TABLE "property_media" ADD CONSTRAINT "FK_property_media_property_id" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shortlist" ADD CONSTRAINT "FK_shortlist_propertyId" FOREIGN KEY ("propertyId") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shortlist" ADD CONSTRAINT "FK_shortlist_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "properties" ADD CONSTRAINT "FK_properties_building" FOREIGN KEY ("building_id") REFERENCES "buildings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "properties" ADD CONSTRAINT "FK_properties_operator_id" FOREIGN KEY ("operator_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buildings" ADD CONSTRAINT "FK_buildings_operator" FOREIGN KEY ("operator_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "operator_profiles" ADD CONSTRAINT "FK_operator_profiles_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_profiles" ADD CONSTRAINT "FK_tenant_profiles_userId" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "preferences" ADD CONSTRAINT "FK_preferences_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
